namespace: cp4aiops

gitops:
  namespaceScoped: false

catalog:
  name: ibm-aiops-catalog
  image: icr.io/cpopen/ibm-aiops-catalog@sha256:29bb9e7da9bed58948dcae74a22ce542748acba6f18b64c27875c1db3ac7db53

subscription:
  name: ibm-aiops-orchestrator
  channel: v5.1

installation:
  name: ibm-cp-aiops
  spec:
    size: large
    storageClass: ocs-storagecluster-cephfs
    storageClassLargeBlock: ocs-storagecluster-ceph-rbd
    topologyModel: application
    license:
      accept: ''
    pakModules:
    - name: aiopsFoundation
      enabled: true
    - name: applicationManager
      enabled: true
    - name: aiManager
      enabled: true
    - name: connection
      enabled: false
    - name: logAnomalyDetection
      enabled: false