namespace: cp4aiops

gitops:
  namespaceScoped: false

catalog:
  name: ibm-aiops-catalog
  image: icr.io/cpopen/ibm-aiops-catalog@sha256:b62d055109cbb0231ad11422f8eff0b4f02e4bcaa8c9a3a3bfc5bff8318f7343

subscription:
  name: ibm-aiops-orchestrator
  channel: v5.1

installation:
  name: ibm-cp-aiops
  namespace: cp4aiops
  spec:
    size: large
    storageClass: ocs-storagecluster-cephfs
    storageClassLargeBlock: ocs-storagecluster-ceph-rbd
    topologyModel: application
    license:
      accept: ''
    pakModules:
    - name: aiopsFoundation
      enabled: true
    - name: applicationManager
      enabled: true
    - name: aiManager
      enabled: true
    - name: connection
      enabled: false
    - name: logAnomalyDetection
      enabled: false
    zones:
    - name: ''
    - name: ''
    - name: ''
