apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cp4aiops-role
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups: ["orchestrator.aiops.ibm.com"]
    resources: ["installations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cp4aiops-rolebinding
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-cp4aiops-role
  apiGroup: rbac.authorization.k8s.io