apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: cp4aiops-operator-group
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  targetNamespaces:
    - {{.Values.namespace}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{.Values.subscription.name}}
  namespace: {{.Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  channel: {{.Values.subscription.channel}}
  installPlanApproval: Automatic
  name: {{.Values.subscription.name}}
  source: {{.Values.catalog.name}}
  sourceNamespace: {{.Values.namespace}}
