catalog:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:435b47b0441486d80c06c5cea6f2182367bc5bcedd2fb92bda24b3be9887e020
subscription:
  name: ibm-cert-mgr
  namespace: ibm-cert-manager
  channel: v4.2